"""Project inventory — the list of everything being built, plus a three-field
interview story and a five-item ship checklist per project.

`db` owns the rows; this module owns the completeness math, the core/other split and
the Markdown export. Nothing here writes story text: the three story blanks + a
5-item ship checklist are the user's to fill, and an empty bar is the signal that
they still need filling.
"""
import json
import os
from datetime import date
from pathlib import Path

import db
from agent.resume_tailor import _chat_json

STORY_FIELDS = ("problem", "built", "result")

# Labels and prompts live here rather than in the view so the export and the UI
# cannot drift apart.
STORY_LABELS = {
    "problem": "Problem",
    "built": "What I built",
    "result": "Result & numbers",
    "pitch": "30-second pitch",
}
STORY_PROMPTS = {
    "problem": "What was broken or missing before this existed?",
    "built": "The system in three sentences — what it does, not how proud you are.",
    "result": "What changed. Put a number on it — uptime, latency, hours saved, units shipped.",
    "pitch": "Say it out loud. If it takes longer than 30 seconds, cut it.",
}
SHIP_ITEMS = (("repo", "Public GitHub repo"), ("readme", "README with screenshot/GIF"),
              ("demo", "Demo video / photos"), ("bullet", "Resume bullet with a number"),
              ("portfolio", "On portfolio site"))


def _filled(row, field):
    return bool((row.get(field) or "").strip())


def ship_state(row):
    raw = row.get("ship")
    try:
        data = json.loads(raw) if isinstance(raw, str) else (raw or {})
    except ValueError:
        data = {}
    if not isinstance(data, dict):
        data = {}
    return {k: bool(data.get(k)) for k, _ in SHIP_ITEMS}


def story_filled(row):
    return sum(1 for f in STORY_FIELDS if _filled(row, f))


def completeness(row):
    return round(story_filled(row) / len(STORY_FIELDS) * 100)


def decorate(row):
    ship = ship_state(row)
    return {**row, "ship": ship, "ship_done": sum(ship.values()),
            "story_filled": story_filled(row), "completeness": completeness(row)}


def overall(rows):
    """Percent is story fields filled across core projects, not projects finished:
    writing 1 of 3 blanks should move the bar, or it sits at 0 for weeks and stops
    being motivating. `complete_count` carries the "7 of 18 done" reading; `shipped_count`
    is projects with all 5 ship-checklist items checked."""
    core = [r for r in rows if r.get("tier") == "core"]
    total_fields = len(core) * len(STORY_FIELDS)
    filled = sum(story_filled(r) for r in core)
    return {
        "percent": round(filled / total_fields * 100) if total_fields else 0,
        "complete_count": sum(1 for r in core if completeness(r) == 100),
        "shipped_count": sum(1 for r in core if all(ship_state(r).values())),
        "total": len(core),
    }


def all_grouped():
    rows = db.projects_all()
    return {
        "core": [decorate(r) for r in rows if r.get("tier") == "core"],
        "other": [decorate(r) for r in rows if r.get("tier") != "core"],
        "overall": overall(rows),
    }


def set_tier(pid, tier):
    if tier not in ("core", "other"):
        return None
    row = db.project_update(pid, {"tier": tier})
    return decorate(row) if row else None


# ── roots ───────────────────────────────────────────────────────────────────────
# Project `path`s are relative to ASCENT_PROJECTS_ROOT (default: your home folder),
# and Draft with Linda only reads files inside it. PROJECTS.md is written into that
# root when the variable is set, otherwise next to the database (gitignored).
_ROOT_ENV = os.environ.get("ASCENT_PROJECTS_ROOT")
PROJECTS_ROOT = Path(_ROOT_ENV).expanduser() if _ROOT_ENV else Path.home()

# ── Markdown export ─────────────────────────────────────────────────────────────
PROJECTS_MD = (PROJECTS_ROOT if _ROOT_ENV else Path(db.DB_PATH).parent) / "PROJECTS.md"

BLANK = "_(blank)_"


def _index_table(rows):
    out = ["| Project | Status | Stack | Path | Story |", "|---|---|---|---|---|"]
    for r in rows:
        out.append(f"| {r['name']} | {r.get('status') or ''} | {r.get('stack') or ''} "
                   f"| `{r.get('path') or ''}` | {r['story_filled']}/3 · {r['ship_done']}/5 shipped |")
    return "\n".join(out)


def render_markdown():
    g = all_grouped()
    o = g["overall"]
    parts = [
        "# Projects",
        "",
        "> Generated by Ascent's Projects section — **this file is overwritten on every "
        "export.** Edit the cards in Ascent, not here.",
        f"> Generated {date.today().isoformat()} · {o['percent']}% of story fields written · "
        f"{o['shipped_count']} of {o['total']} core projects fully shipped.",
        "",
        "## Index",
        "",
        _index_table(g["core"]),
        "",
        "### Other / dormant",
        "",
        _index_table(g["other"]),
        "",
        "---",
    ]
    for r in g["core"]:
        parts += [
            "",
            f"## {r['name']}",
            "",
            f"`{r.get('path') or ''}` · {r.get('stack') or ''} · {r.get('status') or ''} "
            f"· {r['completeness']}% written",
            "",
            r.get("purpose") or "",
        ]
        for f in STORY_FIELDS:
            parts += ["", f"### {STORY_LABELS[f]}", "", (r.get(f) or "").strip() or BLANK]
        if (r.get("pitch") or "").strip():
            parts += ["", f"### {STORY_LABELS['pitch']}", "", r["pitch"].strip()]
    return "\n".join(parts) + "\n"


def export_markdown():
    PROJECTS_MD.write_text(render_markdown(), encoding="utf-8")
    return str(PROJECTS_MD)


# ── Linda draft ─────────────────────────────────────────────────────────────────
DRAFT_SOURCES = ("README.md", "CLAUDE.md", "package.json", "pyproject.toml")
DRAFT_CAP = 6000
DRAFT_SYSTEM = (
    "You write interview-ready project stories for an engineer's resume. Use ONLY facts in the "
    "provided files; never invent numbers — if none are given, say what to measure. Return JSON "
    'with exactly these string keys: "problem" (1-2 sentences), "built" (<=3 sentences), '
    '"result" (1-2 sentences), "bullet" (one resume bullet starting with a verb).')


class DraftError(Exception):
    def __init__(self, status, message):
        super().__init__(message)
        self.status, self.message = status, message


def _source_dir(path):
    """The project folder, resolved (symlinks and `..` included) and required to sit
    inside PROJECTS_ROOT, so a crafted path can't make Linda read arbitrary files."""
    root = PROJECTS_ROOT.resolve()
    base = (root / Path(path).expanduser()).resolve()
    if base != root and root not in base.parents:
        raise DraftError(403, f"{path} is outside the projects root ({root}); set ASCENT_PROJECTS_ROOT")
    return base


def _source_text(path):
    base = _source_dir(path)
    chunks = []
    for name in DRAFT_SOURCES:
        f = base / name
        if f.is_file():
            try:
                chunks.append(f"--- {name} ---\n{f.read_text(encoding='utf-8', errors='replace')}")
            except OSError:
                continue
    return "\n\n".join(chunks)[:DRAFT_CAP]


def draft(pid):
    row = db.project_get(pid)
    if not row:
        raise DraftError(404, "project not found")
    path = (row.get("path") or "").strip()
    if not path:
        raise DraftError(422, "no README/CLAUDE.md under (no path set)")
    src = _source_text(path)
    if not src.strip():
        raise DraftError(422, f"no README/CLAUDE.md under {row.get('path') or '(no path set)'}")
    user = f"Project: {row['name']}\nStack: {row.get('stack') or ''}\n\n{src}"
    try:
        out, _, _ = _chat_json(DRAFT_SYSTEM, user)
    except ValueError as exc:
        raise DraftError(502, f"Linda returned bad JSON: {exc}")
    except Exception as exc:  # ollama connection / timeout errors vary by version
        raise DraftError(503, f"Ollama unreachable — is it running? ({exc})")
    return {k: str(out.get(k) or "").strip() for k in ("problem", "built", "result", "bullet")}
